### ISSUE TITLE
Crash when loading Cloanto kickrom

### ISSUE THREAD

**Issue by mdbergmann** [emufreak/iAmiga#35]
Hi.

I've tried the emulator (1.1.0) with Cloanto roms.
When starting the Emulator I'm getting a EXC_BAD_ACCESS error in zfile.cpp method:
size_t uae4all_rom_fread(void *ptr, size_t tam, size_t nmiemb, FILE *flujo)

```
size_t uae4all_rom_fread(void *ptr, size_t tam, size_t nmiemb, FILE *flujo)
{
    if ((!flujo)||(!uae4all_rom_memory))
        return 0;
    if (uae4all_rom_pos>=uae4all_rom_len)
        return 0;
=> here memcpy(ptr,(void *)(((unsigned)uae4all_rom_memory)+((unsigned)uae4all_rom_pos)),tam*nmiemb);
    uae4all_rom_pos+=tam*nmiemb;
    return nmiemb;
}
```

Is using Cloanto ROMs supported?

Manfred

**Comment by simontoens** [comment]
Hi @mdbergmann, I _think_ the answer is that you are the first one to try and so given your experience, I guess Cloanto ROMs are not supported.  Would you like to try to contribute a fix?

**Comment by mdbergmann** [comment]
I can have a look. But that'll take a while.

**Comment by emufreak** [comment]
What Version of Cloanto Amiga Forever do you use?

**Comment by mdbergmann** [comment]
It's at least 2013, possibly newer.

**Comment by emufreak** [comment]
@mdbergmann. Sorry that's not what I meant. Is it Value, Plus or Premium Edition . Problems were reported with other emulators with Value Edition.

**Comment by mdbergmann** [comment]
I have the Plus edition.

**Comment by emufreak** [comment]
@mdbergmann Should work too. Can't test it though. Can you give it a go?

**Comment by mdbergmann** [comment]
Didn't work in my test. The screen stays black.
The Cloanto roms come with a rom.key file.
Probably they are encrypted.
Is that key file loaded at all?

**Comment by emufreak** [comment]
I'm working on this. There are still some bugs but I got the general idea.

**Comment by emufreak** [comment]
Hi @mdbergmann 

I fixed this. You'll have to add rom.key using Itunes. Then you should be able to load the Cloanto rom.

Please confirm
