### ISSUE TITLE
256k ROMs don't work

### ISSUE THREAD

**Issue by mdbergmann** [emufreak/iAmiga#36]
Hi.

Sorry to open an issue for this.
I'll gladly write to a mailing list or something else if available.

I'd really like to get iUAE running.
Here is my problem:
- downloaded the sources for 1.1.0.
- added kick13.rom to bundle (it is found and read on emulator startup, rom was extracted from a real a500).
- added workbench 1.34 adf to bundle.
- build and run on iPad mini 4
  all I get is a grey screen after a few seconds but nothing more.
  enabling the LEDs I see 5 LEDs. The red one is flashing in a certain frequency.
  Resetting doesn't help.
  Inserting an adf doesn't help.
  There is just this grey screen and the red LED flashing.
  I've enabled DEBUG_UAE4ALL and DEBUG_MEMORY but I couldn't really see any issues.
  I've removed the run script phase for the OpeniOSDev stuff. Is this required?

Cheers,
Manfred

**Comment by mithrendal** [comment]
The removal of the runscript is correct. Did you try the dev branch?

**Comment by mdbergmann** [comment]
Yeah, I've tried the dev branch just now.
Same problem.

**Comment by simontoens** [comment]
Does the same thing happen when you run in a simulator?  Does this rom you are using work fine with other Amiga emulators (for example FS-UAE)?

**Comment by mdbergmann** [comment]
The exact same thing happens on the simulator, it's just a bit quicker until the grey screen comes up.
The rom works fine on fs-uae.

I can see the grey screen on fs-uae as well, after it however would come the PAL white screen with the 1.3 disk hand.
It seems it's stuck somewhere.

**Comment by simontoens** [comment]
hmmm weird, I don't have any good idea on how to debug this further, apart from trying a different rom...

**Comment by mdbergmann** [comment]
Can you send me a rom that works for you?
Then we can confirm it's because of the rom.
If that's really the problem then uae4all should really be tweaked to accept more roms.

**Comment by mdbergmann** [comment]
OK, I found a 1.3 ROM that works.
But it's strange. My original A500 ROM is 256 kB this one I got elsewhere is 512kB. Also all the Cloanto ROMs for v1.0-1.4 are all 256kB in size.
It looks like the rom loading code is not very mature.

Every though of using uae4all2?

**Comment by simontoens** [comment]
Glad you got it working at least.  It is possible that the rom loading code is not using the latest from uae4all2 - it may be worthwhile to compare the code.

**Comment by simontoens** [comment]
@mdbergmann based in your findings, could you update this issue's title to something like: "256k roms don't work"?

**Comment by emufreak** [comment]
I made a quick research uae4all2 does support 256k roms. So it would be possible to port this

**Comment by emufreak** [comment]
@mdbergmann I fixed this in my latest commit to dev. Can you confirm?

**Comment by mdbergmann** [comment]
I can confirm that my extracted original A500 v1.3 256k rom does work now.

Thanks

**Comment by mithrendal** [comment]
Nice. Good work. 👍
