### ISSUE TITLE
Add option to eject disks

### ISSUE THREAD

**Issue by mdbergmann** [emufreak/iAmiga#37]
I can't see where to eject disks.
Would be good to add this.

**Comment by simontoens** [comment]
You can left-swipe on the drive row to eject.  One of these days we'll need to write some documentation.

**Comment by mdbergmann** [comment]
OK, thanks.
The Wiki?

**Comment by emufreak** [comment]
I could add it on iua-emulator.net in the FAQs section. I didn't know about this myself actually :-)

**Comment by simontoens** [comment]
@emufreak I think we could just use the wiki here?  It seems nice to manage everything in a single place.  I was actually just going to add more info in README.md.  The benefit of README.md is that everybody can edit (and submit pull requests)

**Comment by simontoens** [comment]
@mdbergmann could you close this issue?
