### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by mdbergmann** [emufreak/iAmiga#41]
Hi.
I have no sound in iUAE on my iPad mini 4.
Must this be switched on somewhere?

Manfred

**Comment by simontoens** [comment]
No, sound is always on.  Do you have any other iDevices you can test the emulator on?  I doubt this is related to running on an iPad mini 4 but I cannot say for sure because I don't have one.

**Comment by mdbergmann** [comment]
Sorry. I had my iPad in silent mode.
Sound is working OK.
