### ISSUE TITLE
Add rom file selector

### ISSUE THREAD

**Issue by simontoens** [emufreak/iAmiga#44]
So that users can switch roms easily.

**Comment by emufreak** [comment]
Would be really useful

**Comment by simontoens** [comment]
I am working on this now

**Comment by emufreak** [comment]
Association from .rom files might be a good Idea too. Could this be done in the process?

**Comment by simontoens** [comment]
What do you mean by association?

**Comment by emufreak** [comment]
That files can get imported to iUAE after Download or from AirDrop

**Comment by simontoens** [comment]
Sure I can add that.

**Comment by simontoens** [comment]
@emufreak I am closing this, let me know if you want me to change something.
