### ISSUE TITLE
iUAE v1.2 

### ISSUE THREAD

**Issue by emufreak** [emufreak/iAmiga#53]
I'd like to make a new release containing the new Features from dev.

Is there anything you think has to be done before releasing it.

Personally I'd like to have Issue "Emulator states don't restore hd state" fixed for this release but it's not a must.

It's already packed with many great new features, so I don't see anything to be done there.

**Comment by simontoens** [comment]
I agree there are a lot of new features that are worth releasing.  

I have not looked yet at how much work it is to get the state restoring working with hd - I am assuming this works fine with uae4all2 and it is just a matter of copying over/tweaking  more files, but I have not verified, and I don't have time in the near future to look at this.  Unless you have time, I'd vote for releasing without a fix for this issue.

**Comment by mithrendal** [comment]
I would like to have more time for this, but recently I am busy as never before... Beside this feel free to go. ;-) Only one more issue that I discovered but not yet added to our issues list. When I tested the accelerometer joystick feature from stargazer, I found that it did not work remote controlled. The original version of stargazer did work correctly remote-controlled in the beginning, but then some code of it moved to the MPC Controller and that did possibly broke it. @emufreak maybe you like to fix it before releasing 1.2?

**Comment by emufreak** [comment]
I think I fixed the remote controlled accelerometer recently. I think I'll release this after some more tests next week.

**Comment by mithrendal** [comment]
@emufreak I tested it about two moths ago. If you fixed it recently then its fine.

**Comment by emufreak** [comment]
Finally was able to package for cydia store 

-Support for Multiple Joypads
-Use your Idevice as a Joypad
-Gyroscope option for Vpad
-HD Support
-Kickstart Rom Selector
-Support for Cloanto Amiga Forever Roms and 256k Roms
-Improvement in Memory handling
-Many small improvements

**Comment by simontoens** [comment]
Awesome @emufreak thanks!  btw do you have any idea of how many downloads you are getting for iUAE?  Just curious whether we can tell how many users there are.

Should I merge dev into master or are you already doing it?

**Comment by emufreak** [comment]
I just know about the Cydia downloads. Checkout http://apt.thebigboss.org/stats?dev=emufr3ak. I think the popularity of Version 1.0.5 is due to the fact, that it was just released after a Jailbreak for iOS 8 was available. 

No Idea how many people download from my website (No way to find out for Google Sites) or from Github.
