### ISSUE TITLE
Hires bitplanes 2 to 5 not drawn at the first horizontal 16 pixels 

### ISSUE THREAD

**Issue by mithrendal** [emufreak/iAmiga#62]
![img_8390](https://cloud.githubusercontent.com/assets/17108995/21589396/8e881844-d0f1-11e6-9f36-468b748ec13f.PNG)

You see this clearly at the empty/full bar. 

![img_8389](https://cloud.githubusercontent.com/assets/17108995/21589424/e65b54e6-d0f1-11e6-9363-4c08c779dcf8.PNG)

Here I dragged the window some pixel more to the right. 

@emufreak @simontoens @mdbergmann  could someone confirm that it's a bug not only in my environment.  These are still pics from the unpatched emu-core (e.g. Shrinked hires to lores). I want to be sure that I didn't broke it before I bring out the hires patch.

**Comment by mithrendal** [comment]
I have fixed this issue with this commit 72c6daaa1233b81dc7b973e22d9a1a273c11fa54 . The commit is part of the current pull request.

@simontoens @mdbergmann @emufreak

**Comment by mithrendal** [comment]
![img_8394](https://cloud.githubusercontent.com/assets/17108995/21725155/7940b5d8-d437-11e6-8c7d-c7003417b1e1.PNG)

Now it looks gorgeous, doesn't it?

**Comment by simontoens** [comment]
Looks great @mithrendal!

(also happy to see you are a fellow WB 1.2 user - as opposed to 1.3 :)

**Comment by mithrendal** [comment]
Next is the speed issues in cinemaware apps. I have an idea. It may be conjuncted to the fact that our emu doesn't draw all of the 256 PAL lines. It is restricted to draw only 240 which may also still include some offscreen pixels.  Seems the output is restricted to NTSC. That may affect the vertical blank timing. And that in consequence may affect the timing of amiga apps when they rely on vblank timing. Will try this out today or tomorrow. @simontoens

**Comment by simontoens** [comment]
I wish I knew more about the emulator internals...I am glad you do - so are you saying that we don't support PAL mode correctly?  Although I am always running in PAL mode..

**Comment by mithrendal** [comment]
Yeah maybe. Just look at drawings.cpp 
#define GFXVIDINFO_HEIGHT 240
#define MAXBLOCKLINES 240

It does not draw more than 240 lines even if you are running in PAL. You also see this when you run for example deluxe paint and choose a 320x256 screen. You see there that the very bottom of the screen is left out.

But whether this also affects the vblank timing has to be seen...  I will look into that the next days or so...
