### ISSUE TITLE
iUAE 1.3

### ISSUE THREAD

**Issue by emufreak** [emufreak/iAmiga#68]
I think we are ready for a new release. The dev-branch now contains the following new features (Please tell me if something is missing):

-Correctly working hires mode (thanks again @mithrendal)
-Better usage of screen space resulting in larger image
-Some fixes for dual playfield
-Configurable Memory

Please play around it a bit and tell me if you find any issues till the end of next week

**Comment by emufreak** [comment]
Just commited a fix to support 64bit-compilation. This needs more testing (on 32bit and 64bit devices). I'll probably not release this version to the public till may.

**Comment by mithrendal** [comment]
Really fantastic news!!! Will check it out in the coming days. Thank you so much 😊.

**Comment by dobrynski** [comment]
Is the 1.3 release still forthcoming?

**Comment by emufreak** [comment]
1.3 release is the last stable version.
