### ISSUE TITLE
Submodule StObjCToolbelt missing?

### ISSUE THREAD

**Issue by Blackmaster117** [emufreak/iAmiga#74]
This Submodule seems to no longer exist making this project uncompilable. :(

**Comment by mithrendal** [comment]
the submodule was hosted at simons repo

https://github.com/simontoens/STObjCToolbelt

@simontoens any reason you deleted it ?

**Comment by simontoens** [comment]
I deleted it because it was crap, but I forgot it is used by this project.  Let me see if I can bring it back.

**Comment by simontoens** [comment]
It was private, now it is public again, sorry about that: https://github.com/simontoens/STObjCToolbelt
